feat: add IPv6 support with configurable option and fix deployment issues (#711)
* Feat: IPv6 + fixes

* fix: syntax issues

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -70,8 +70,20 @@ done
 . ./lib/cli/terraform.sh
 . ./lib/cli/ansible.sh
 
+# Determine the Dash network type from the network name
+if [[ "$NETWORK_NAME" == "testnet" ]]; then
+    DASH_NETWORK_TYPE="testnet"
+elif [[ "$NETWORK_NAME" == "mainnet"* ]]; then
+    DASH_NETWORK_TYPE="mainnet"
+elif [[ "$NETWORK_NAME" == "devnet"* ]]; then
+    DASH_NETWORK_TYPE="devnet"
+else
+    echo "Error: Unable to determine network type from network name: $NETWORK_NAME"
+    exit 1
+fi
+
 # Ensure the network name is passed correctly to firstRun.js
-node ./bin/firstRun.js ${NETWORK_NAME} || exit
+node ./bin/firstRun.js ${DASH_NETWORK_TYPE} ${NETWORK_NAME} || exit
 
 case ${STAGE} in
     1)
