fix: improve error handling (#622)
Co-authored-by: ktechmidas <daniel@ktechmidas.net>

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -60,11 +60,17 @@ case ${STAGE} in
     1)
         echo "Deploying $NETWORK_NAME network... stage (1)";
 
-        # TODO: this fails if not at the HEAD of a given branch
-        BRANCH=$(git symbolic-ref --short HEAD)
-        if [[ $BRANCH == "devnet-"* ]]; then
-            if [[ $BRANCH != $NETWORK_NAME ]] && [[ $FORCED_DEPLOYMENT != 1 ]]; then
-                echo "Wrong Devnet - Check you're in the correct branch. Use -f to force if you're sure"
+        if [[ $FORCED_DEPLOYMENT != 1 ]]; then
+            if git symbolic-ref --quiet HEAD 2>/dev/null; then
+                BRANCH=$(git symbolic-ref --short HEAD)
+                if [[ $BRANCH == "devnet-"* ]]; then
+                    if [[ $BRANCH != $NETWORK_NAME ]]; then
+                        echo "Wrong Devnet - Check you're in the correct branch. Use -f to force if you're sure"
+                        exit 1
+                    fi
+                fi
+            else
+                echo "Unable to make sure you're not deploying onto a bad network because the head is detached! Please use -f"
                 exit 1
             fi
         fi
